OCAMLMAKEFILE = ../OCamlMakefile

OCAMLOPT=ocamlopt.opt

INCDIRS=../../poclow ../../poccore ../../pociface ../../extlib-1.3 ../../xml-light2.1 ../../cryptokit-1.2 ../../lua-ml ../
LIBS=poclow xml-light extLib str nums lua-std poccore pociface pocgame

SOURCES = engine.ml
THREADS=yes
RESULT=pocengine

all: nc

include $(OCAMLMAKEFILE)